repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Update this version to the latest release
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0 # Update this version to the latest release
    hooks:
      - id: flake8
        files: src/
        args: [
          "--exclude=.venv",
          "--ignore=E203,E266,E501,W503,F403,F401",
          "--max-line-length=80",
          "--max-complexity=18",
          "--select=B,C,E,F,W,T4,B9"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1  # Update this version to the latest release
    hooks:
      - id: mypy
        name: mypy (src)
        args: [--show-error-codes, '--ignore-missing-imports','--cache-dir', 'backend/.mypy_cache']
        files: src/ #ensures that mypy only checks files within the src directory.
        #pass_filenames: false #disables passing file names to mypy, allowing it to discover files on its own within the specified directory.
        language_version: python3 #sets the Python version to use for the mypy hook.
        additional_dependencies: [toml, types-requests, types-PyYAML, pydantic] # includes packages as an additional dependency for the mypy pre-commit hook.

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Use the latest version of isort
    hooks:
      - id: isort
        additional_dependencies: [toml]
        files: src/

  - repo: https://github.com/ambv/black
    rev: 23.1.0  # Update this version to the latest release
    hooks:
      - id: black
        files: src/
